### ISSUE TITLE
Add examples on generating with sound

### ISSUE THREAD

**Issue by revodavid** [microsoft/aitour-interact-with-llms#34]
To fully embrace the multimodal aspect of GPT-4o, add some examples using and generating audio data.

With that update, here is a new abstract (289 characters):

Innovate with Azure OpenAI's GPT-4o multimodal model in this hands-on experience. Learn the core concepts to and best practices to effectively generate with text, sound and images. Experience creating AI assistants with function calling that enhance user experiences and drive innovation.

**Comment by BethanyJep** [comment]
Thanks @revodavid, will include in the multimodality section.

**Comment by BethanyJep** [comment]
Hello, looked into this and currently gpt-4o audio ``gpt-4o-realtime-preview`` is not yet supported in the playground. We will update the workshop once support is added.

**Comment by BethanyJep** [comment]
The new Audio playground is live, will update the new workshop on the Microsoft-Ignite-updates branch.
